# Libraries

Import the necessary libraries for the project

In [1]:
# Libraries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Import dataset

➡️ 1. Import the dataset which is the the following location.

- Stoage it as `df`
- The dataframe doesn't have headers

🔴 Note: the dataframe doesn't have.

<details><summary>Solution</summary>

```python
df = pd.read_csv(path, header= None)
```

In [2]:
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"

In [3]:
# Answer
df = pd.read_csv(path, header= None)

➡️ 2. Use the list below to set the header of the imported df.

In [4]:
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]

<details><summary>Solution</summary>

```python
df.columns = headers
```

In [5]:
# Answer
df.columns = headers

# Inspection

➡️ 3. Display a glance of the first 7 register of the dataframe

<details><summary>Solution</summary>

```python
df.head(7)
```

In [6]:
# Answer
df.head(7)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710

➡️ 4. What is the shape of the dataframe?

<details><summary>Solution</summary>

```python
df.shape
```

In [7]:
# Answer
df.shape

(205, 26)

➡️ 5. Give a statistics summary of the dataframe, including the Object-typed columns.

<details><summary>Solution</summary>

```python
df.describe(include="all")
```

In [8]:
# Answer
df.describe(include="all")

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
count,205.000000,205,205,205,205,205,205,205,205,205.000000,...,205.000000,205,205,205,205.000000,205,205,205.000000,205.000000,205
unique,NaN,52,22,2,2,3,5,3,2,NaN,...,NaN,8,39,37,NaN,60,24,NaN,NaN,187
top,NaN,?,toyota,gas,std,four,sedan,fwd,front,NaN,...,NaN,mpfi,3.62,3.40,NaN,68,5500,NaN,NaN,?
freq,NaN,41,32,185,168,114,96,120,202,NaN,...,NaN,94,23,20,NaN,19,37,NaN,NaN,4
mean,0.834146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.756585,...,126.907317,NaN,NaN,NaN,10.142537,NaN,NaN,25.219512,30.751220,NaN
std,1.245307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.021776,...,41.642693,NaN,NaN,NaN,3.972040,NaN,NaN,6.542142,6.886443,NaN
min,-2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,...,61.000000,NaN,NaN,NaN,7.000000,NaN,NaN,13.000000,16.000000,NaN
25%,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,...,97.000000,NaN,NaN,NaN,8.600000,NaN,NaN,19.000000,25.000000,NaN
50%,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,...,120.000000,NaN,NaN,NaN,9.000000,NaN,NaN,24.000000,30.000000,NaN
75%,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,...,141.000000,NaN,NaN,NaN,9.400000,NaN,NaN,30.000000,34.000000,NaN
max,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,...,326.000000,NaN,NaN,NaN,23.000000,NaN,NaN,49.000000,54.000000,NaN

➡️ 6. Delimitate the summary to the columns `make` and `price`.

<details><summary>Solution</summary>

```python
df[['make','price']].describe()
```

In [9]:
# Answer
df[['make','price']].describe()

          make price
count      205   205
unique      22   187
top     toyota     ?
freq        32     4

➡️ 7. Print the data type of each variable?

🟠 Pay attention to price.

<details><summary>Solution</summary>

```python
df.dtypes
```

In [10]:
# Answer
df.dtypes

symboling              int64
normalized-losses        str
make                     str
fuel-type                str
aspiration               str
num-of-doors             str
body-style               str
drive-wheels             str
engine-location          str
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type              str
num-of-cylinders         str
engine-size            int64
fuel-system              str
bore                     str
stroke                   str
compression-ratio    float64
horsepower               str
peak-rpm                 str
city-mpg               int64
highway-mpg            int64
price                    str
dtype: object

# Missing values

➡️ 8. Replace the `?` for `Nan` values in the WHOLE dataframe.

🔴 Make sure to replace inplace.

<details><summary>Solution</summary>

```python
df.replace("?", np.nan, inplace= True)
```

In [23]:
# Answer
df.replace("?", np.nan, inplace= True)
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450

➡️ 9. Display how many `NaN` values are per column.

<details><summary>Solution</summary>

```python
df.isnull().sum()
```

In [30]:
# Answer
df.isnull().sum()[df.isnull().sum()>0]

Series([], dtype: int64)

## Dealing with Missing values

➡️ 10. For the following variables:

```python
"normalized-losses", "stroke", "bore", "horsepower", "peak-rpm"
```

Replace missing values with the **mean** value of each variable.

🟢 Temporaly, transform them into "float" for the local calculation.

🟠 Use the `axis=0` for get the mean, to get in familiar.

🟠 Remember to use `inplace` for the replacement.

<details><summary>Solution</summary>

```python
col_rep_mean = ["normalized-losses", "stroke", "bore", "horsepower", "peak-rpm"]

for i in col_rep_mean:
    df[i] = pd.to_numeric(df[i], errors='coerce')
    df[i] = df[i].fillna(df[i].mean())
```

In [25]:
# Answer
col_rep_mean = ["normalized-losses", "stroke", "bore", "horsepower", "peak-rpm"]

for i in col_rep_mean:
    df[i] = pd.to_numeric(df[i], errors='coerce')
    df[i] = df[i].fillna(df[i].mean())

➡️ 11. for the variable `num-of-doors`,  replace the `NaN` with the most frequent value.

🟢 Inspect the frequency of the values of this variable.

👉 Extra: if you display the max id automatically.

<details><summary>Solution</summary>

```python
df['num-of-doors'].value_counts()
door_frq = df['num-of-doors'].value_counts().idxmax()
df['num-of-doors'].replace(np.nan, door_frq, inplace= True)
```

In [29]:
# Answer
df['num-of-doors'].value_counts()
door_frq = df['num-of-doors'].value_counts().idxmax()
df['num-of-doors'] = df['num-of-doors'].fillna(door_frq)

➡️ 12. Drop the register where price is `NaN`

🟠 Remember to reset the index after that.

<details><summary>Solution</summary>

```python
df.dropna(subset=['price'], axis= 0, inplace= True)
df.reset_index(drop=True, inplace = True)
```

In [18]:
# Answer
df.dropna(subset=['price'], axis= 0, inplace= True)
df.reset_index(drop=True, inplace = True)

📘 13. Save the current dataset as `df_nomiss.csv`

In [31]:
df.to_csv("1_Data/df_nomiss.csv", index= False)

In [32]:
df = pd.read_csv("1_Data/df_nomiss.csv")

# Correct Data types

📘 14. Perform the adjustment of the variables on the table according to the type required.

| Type | Columns |
| ----- | ----------------------------------- |
| float | 'bore,'stroke', 'price', 'peak-rpm' |
| int   | "normalized-losses",                |

<details><summary>Solution</summary>

```python
cols_float = ["bore", "stroke", "price", "peak-rpm"]
cols_int = ["normalized-losses"]

df[cols_float] = df[cols_float].astype('float')
df[cols_int] = df[cols_int].astype('int')
```

In [33]:
# Answer
cols_float = ["bore", "stroke", "price", "peak-rpm","horsepower"]
cols_int = ["normalized-losses"]

df[cols_float] = df[cols_float].astype('float')
df[cols_int] = df[cols_int].astype('int')

📘 15. Transform the variable `horsepower` into integer. Then group the value into 3 levels: Low, Medium, High. For that you need to create four reference point.

1. Create a bins, according to the max and min value for the reference point.
2. Group the values into this two.

<details><summary>Solution</summary>

```python
df["horsepower"] = df["horsepower"].astype("int")

bins = np.linspace(min(df["horsepower"]), max(df["horsepower"]), 4)
group_names = ['Low', 'Medium', 'High']
df['horsepower-binned'] = pd.cut(df['horsepower'],
                                 bins, labels=group_names, include_lowest=True)
df["horsepower-binned"].value_counts()
```

In [35]:
df["horsepower"] = df["horsepower"].astype("int")

bins = np.linspace(min(df["horsepower"]), max(df["horsepower"]), 4)
group_names = ['Low', 'Medium', 'High']
df['horsepower'] = pd.cut(df['horsepower'],
                                 bins, labels=group_names, include_lowest=True)
df["horsepower"].value_counts()

horsepower
Low       153
Medium     43
High        5
Name: count, dtype: int64

📘 16. Transform these categorical columns into numeric columns using one-hot encoding:

<details><summary>Solution</summary>

```python
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
```

</details>

In [36]:
categorical_cols = ['engine-location', 'aspiration', 'fuel-type', 'num-of-doors','body-style',
                    'drive-wheels', 'engine-type', 'fuel-system', 'symboling','num-of-cylinders',
                    'horsepower']

In [37]:
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)  # drop_first avoids multicollinearity

📘 17. Save the current version as `df_type_ok.csv`

<details><summary>Solution</summary>

```python
df.to_csv("df_type_ok.csv", index= False)
```

</details>

In [38]:
df.to_csv("1_data/df_type_ok.csv", index= False)

# Feature Scaling

📘 18. Import StandardScaler from `sklearn.preprocessing` and create a `scaler` instance to prepare numeric features for standardization.

<details><summary>Solution</summary>

```python
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
```

</details>

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
scaler = StandardScaler()

📘 19. Use `StandardScaler` to standardize the selected continuous predictors.

<details><summary>Solution</summary>

```python
df[scale_cols] = scaler.fit_transform(df[scale_cols])
```

</details>

In [41]:
scale_cols = [
    'normalized-losses', 'wheel-base', 'length', 'width', 'height',
    'curb-weight', 'engine-size', 'bore', 'stroke', 'compression-ratio',
    'peak-rpm', 'city-mpg', 'highway-mpg']

In [42]:
# Answer
df[scale_cols] = scaler.fit_transform(df[scale_cols])

📘 20. Remove the variable `make`

In [43]:
df.drop("make", axis=1, inplace=True)

📘 20. Save the current df as `auto_ml.csv`

In [44]:
df.to_csv("1_Data/auto_ml.csv", index= False)